Work progress
beata-krasnopolska/CompanyPaymentsProject pull request #1
Opened 2019-11-10 19:36 UTC by beata-krasnopolska

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +        Paycheck paycheck = new Paycheck();
To na pewno nie tutaj, Paycheck, czyli wypłata dotyczy pracownika, a nie firmy

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +        public List<Paycheck> Paychecks = new List<Paycheck>();
Paychecks dotyczą pracownika...

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +        public void AddPayCheck(int personId)
Ładnie, dokładnie o to chodziło. Wyszukujesz pracownika po Id i dodajesz mu pensję :)

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
>      class Company : Person
Klasa firma na pewno nie powinna dziedziczyć po Person, więc tego można się pozbyć. To się przełoży na zmiany dalej, ale to opiszę Ci w odpowiednich miejscach.

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +            var salary = new SalaryCalculator().CalculateSalary(Post);
Tutaj właśnie jest problem wynikający z tego, że odziedziczyłaś po Person. Powinnaś użyć person.Post jako parametr wejściowy.

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +        public void AddPerson(Person person)
Ta funkcja powinna być bardzo prosta, robisz niej skomplikowane rzeczy jak dodawanie stanowiska. Myślę, że w środku powinno być tylko wywołanie _persons.Add(person) :). Czyli dodajesz osobę, którą przesyłasz jako parametr. Same osoby powinnaś tworzyć w funkcji Main i wtedy je dodawać do firmy :).

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Paycheck.cs
> +        public int PersonID { get; set; }
PaycheckId, czyli identyfikator płatności, a nie osoby...

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Paycheck.cs
> +        public decimal Salary { get; set; }
Tutaj raczej bym dodał pole Date, jako public DateTime Date { get; set; } i ustawiał je jak będziesz tworzyła płatność. Na razie tutaj nie potrzeba funkcji ReturnDate. Samą datę będziemy tworzyć również w funkcji Main (jako taką symulację), czyli stworzysz sobie jakieś osoby i dodasz do nich wypłaty z jakimiś fikcyjnymi datami (daty jakichś wypłat).

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Paycheck.cs
> +        public decimal Salary { get; set; }
Nad rozszerzeniami będziemy pracować, bo idzie Ci dość szybko :).

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Person.cs
>      class Person
Ta klasa wydaje się być OK :).

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Post.cs
> +    public enum Post
To też jest raczej OK :), czyli definiujesz możliwe stanowiska w firmie.

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Program.cs
> +            //na konsoli będzie można podać Id pracownika i wtedy w odpowiedzi suma wypłaconych pieniędzy
Podawanie Id pracownika przeniesiemy na sam koniec. Moim zamysłem było to: najpierw tworzymy firmę, potem dodajemy do niej pracowników, a wybranym pracownikom jakieś wypłaty. Dopiero na końcu podajesz Id pracownika, żeby go wyszukać i wypisać na konsolę jakieś potrzebne dane, np. sumę wypłat.

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Program.cs
> +            //na konsoli będzie można podać Id pracownika i wtedy w odpowiedzi suma wypłaconych pieniędzy
Czyli najpierw Company company = new Company();, albo ja bym raczej użył var company = new Company(); bo to co po lewej to kompilator się domyśli :). Poźniej wywołujesz company.AddPerson tak jak to robisz i na końcu dodajesz pracownikom wypłaty, czyli company.AddPaycheck(tutaj_id_pracownika_któremu_dodajesz_wypłatę); Możesz dodać kilku pracowników (tak jak to robisz) i każdemu po jednej, dwie, bądź trzy wypłaty na przykład)

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Program.cs
> +            Paycheck paycheck = new Paycheck();
To niepotrzebne, wypłaty dodajesz jako company.AddPaycheck(tutaj_id);

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/SalaryCalculator.cs
> +    class SalaryCalculator
Prawie dobrze :), niżej dlaczego.

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/SalaryCalculator.cs
> +        public int Salary { get; set; }
Nie potrzebujesz tej właściwości, możesz w każdym cas zrobić return, np. 
case Post.Assistant:
return 200;

2019-11-13 10:32 UTC, bartekpokerbartek commented on CompanyPaymentsProject/SalaryCalculator.cs
> +                    break;
Mamy gwarancję (przy naszych założeniach, że są trzy stanowiska, więc możemy założyć, że w default nigdy nie wejdzie, wobec tego mogła byś rzucać wyjątek: throw new Exception("Post doesn't exist"); - stanowisko nie istnieje.

2019-11-14 19:04 UTC, beata-krasnopolska commented on CompanyPaymentsProject/Company.cs
> +            var salary = new SalaryCalculator().CalculateSalary(Post);
W AddPayCheck nie mam możliwości wybrania „Post” i „Paychecks” po „person.”

2019-11-14 19:06 UTC, beata-krasnopolska commented on CompanyPaymentsProject/SalaryCalculator.cs
> +        public int Salary { get; set; }
po wpisaniu return usunęłam break czy to jest poprawne(Unreachable code)?

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +            var person = _persons.Where(x => x.PersonID == personId);
To jak się głębiej zastanowię to chyba się niezbyt kompiluje ;). Skoro używasz id to musisz uzyskać unikalną osobę, więc użyj tutaj SingleOrDefault(x => x.PersonId == personId);
Zadziała tak jak Ci odpisywałem, jeśli znajdzie to osobę zwróci, jeśli nie to zwróci null, a jeśli znajdzie więcej niż jedną osobę to coś okropnego dzieje się z danymi i dostaniesz exception

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +            person.Paychecks.Add(new Paycheck { Salary = salary });
Nie uzupełniasz daty i paycheckId - jeśli chodzi o drugie to ma to jakiś sens w tym konkretnym przypadku, bo nie zapisujemy do bazy danych i można się pogubić w nadawaniu indexów. Ale może warto jakąś datę sobie generować przypadkową (wpisz np. c# random date w googlach) i coś napisz takiego, ale w osobnej klasie np. RandomDateGenerator. Tutaj tylko to wywołasz i wpiszesz do zmiennej z datą.

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +            return _persons.SingleOrDefault(x=>x.PersonID == personId);
Spacje przed i po =>.

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +            _persons.Add(person);
Tu OK :).

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +            person.Paychecks.Add(new Paycheck { Salary = salary });
Albo zrób zupełnie inaczej: W tej funkcji dodaj parametr wejściowy DateTime date i w funkcji Main jak wywołasz AddPaycheck to tam sobie ustawisz datę, będzie w tym momencie więcej kontroli nad tym co się dzieje.

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Person.cs
> +        public string Name { get; set; }
Rozdzielmy enterami poszczególne właściwości, łatwiej się takie coś czyta.

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Program.cs
> +            company.AddPerson(new Person {PersonID = 1, Name = "Jan", Surname = "Kowalski", Post.Assistant });
Wygląda jakby się nie miało skompilować... nie powinno być Post = Post.Assistant ? Podobnie poniżej? Spacja przed PersonID

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Program.cs
> +            company.AddPerson(new Person {PersonID = 2, Name = "Anna", Surname = "Nowak", Post.Junior,});
Spacja przed PersonId, zamiast przecinka na końcu również spacja.

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Program.cs
> +            company.AddPayCheck(1);
Tutaj jak dodasz datę do funkcji AddPaycheck to będziesz sobie musiała ją tutaj wygenerować, np. new DateTime(2020, 1, 1) czy mniej więcej coś takiego.

2019-11-14 22:31 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Program.cs
OK Id pracownika odczytujesz, ale nie wywołujesz funkcji podającej sumę jego wypłat, a w którejś klasie sobie ją napisałaś.

2019-11-14 22:33 UTC, bartekpokerbartek commented on CompanyPaymentsProject/SalaryCalculator.cs
> +        public int Salary { get; set; }
Tak, jak najbardziej, return powoduje wyjście z funkcji, więc nie wojdzie Ci do kolejnej linijki.

2019-11-14 22:38 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +            var salary = new SalaryCalculator().CalculateSalary(Post);
Jak skorzystasz z SingleOrDefault to będziesz miała tą możliwość, bo w tym momencie próbujesz to wywołać na liście Personów: List<Person>, a to nie lista ma tą właściwość, tylko Person.

2019-11-15 13:19 UTC, bartekpokerbartek requested changes

2019-11-15 13:19 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Company.cs
> +            person.Paychecks.Add(new Paycheck { Salary = salary });
Tutaj Ci opisywałem na Skype, tworzysz dwie płatności, a nie jedną, zerknij sobie i popraw i to chyba ostatnia rzecz :).

2019-11-15 13:19 UTC, bartekpokerbartek commented on CompanyPaymentsProject/Paycheck.cs
> +        public decimal Salary { get; set; }
Tutaj też jeszcze entery pomiędzy właściwościami.

2019-11-18 13:23 UTC, bartekpokerbartek approved these changes

2019-11-18 13:23 UTC, merged